### ISSUE TITLE
Score of two batsmen is same.

### ISSUE THREAD

**Issue by digvijayrdeshmukh** [mukul09/PythonScripts#1]
The score of 1st batsmen is same as that of the same batsmen. at line no 37 following correction is needed:
current code:
message=i['srs']+ "      "+"Format: "+i['type'] +  "\n" + "Score: " +main['batting']['team']+" "+ms['runs'] +'/'+ms['wickets'] +" ("+ms['overs']+")"+"\n" +bat1['name']+":"+bat1['runs']+"("+bat1['balls']+")   "+ bat2['name']+":"+**bat1['runs']**+"("+bat2['balls']+")"

Corrected code:
message=i['srs']+ "      "+"Format: "+i['type'] +  "\n" + "Score: " +main['batting']['team']+" "+ms['runs'] +'/'+ms['wickets'] +" ("+ms['overs']+")"+"\n" +bat1['name']+":"+bat1['runs']+"("+bat1['balls']+")   "+ bat2['name']+":"+**bat2['runs']**+"("+bat2['balls']+")"

**Comment by mukul09** [comment]
Thanks! I'll correct this one
